\i users.sql
\i minerals.sql
\i mineral-data.sql
\i metpetdb-core.sql
\i metpetdb-image.sql
\i metpetdb-chemical-analysis.sql
\i metpetdb-archive.sql
--\i metpetdb-archives-triggers.sql
\i metpetdb-perms.sql
\i minerals.sql
\i elements_and_oxides.sql
\i elements_and_oxides_mineral_types.sql
\i sample-data.sql
\i metpetdb-polygons.sql
\i metamorphic-regions.sql