insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Tectosilicates');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Silica');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Tectosilicates'),(select mineral_id from minerals where name='Silica'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Quartz');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Silica'),(select mineral_id from minerals where name='Quartz'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Coesite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Silica'),(select mineral_id from minerals where name='Coesite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Tridymite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Silica'),(select mineral_id from minerals where name='Tridymite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Cristobalite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Silica'),(select mineral_id from minerals where name='Cristobalite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Feldspar');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Silica'),(select mineral_id from minerals where name='Feldspar'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Plagioclase');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Feldspar'),(select mineral_id from minerals where name='Plagioclase'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Albite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Albite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Albite'), 'Perthite');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Oligoclase');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Oligoclase'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Andesine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Andesine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Labradorite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Labradorite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Anorthite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Anorthite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Alkali feldspar');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Plagioclase'),(select mineral_id from minerals where name='Alkali feldspar'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Alkali feldspar'), 'K-feldspar');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Alkali feldspar'), 'K feldspar');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Alkali feldspar'), 'Alkali-feldspar');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Orthoclase');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Orthoclase'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Orthoclase'), 'Microcline');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Orthoclase'), 'Antiperthite');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sanidine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Sanidine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Celsian');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Celsian'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Nepheline');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Nepheline'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Kalsilite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Kalsilite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Leucite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Leucite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sodalite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Sodalite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Scapolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Scapolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Analcite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Analcite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Zeolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Alkali feldspar'),(select mineral_id from minerals where name='Zeolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sheet silicates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Tectosilicates'),(select mineral_id from minerals where name='Sheet silicates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Mica');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sheet silicates'),(select mineral_id from minerals where name='Mica'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'White Mica');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Mica'),(select mineral_id from minerals where name='White Mica'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Muscovite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Muscovite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Paragonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Paragonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Phengite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Phengite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sericite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Sericite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Margarite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Margarite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Glauconite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Glauconite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Biotite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='White Mica'),(select mineral_id from minerals where name='Biotite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Phlogopite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Phlogopite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Annite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Annite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Wonesite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Wonesite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Lepidolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Lepidolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clintonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Clintonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Stilpnomelane');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Stilpnomelane'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Astrophyllite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Astrophyllite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pyrophyllite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Pyrophyllite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Talc');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Talc'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Chlorite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Chlorite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Serpentine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Serpentine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clay');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Biotite'),(select mineral_id from minerals where name='Clay'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Kaolinite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Kaolinite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Illite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Illite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Smectite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Smectite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Vermiculite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Vermiculite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Montmorillonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Montmorillonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Apophyllite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Apophyllite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Prehnite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clay'),(select mineral_id from minerals where name='Prehnite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Chain silicates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sheet silicates'),(select mineral_id from minerals where name='Chain silicates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pyroxene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Chain silicates'),(select mineral_id from minerals where name='Pyroxene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Orthopyroxene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Pyroxene'),(select mineral_id from minerals where name='Orthopyroxene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Enstatite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthopyroxene'),(select mineral_id from minerals where name='Enstatite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ferrosilite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthopyroxene'),(select mineral_id from minerals where name='Ferrosilite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clinopyroxene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthopyroxene'),(select mineral_id from minerals where name='Clinopyroxene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Calcic pyroxene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clinopyroxene'),(select mineral_id from minerals where name='Calcic pyroxene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Diopside');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic pyroxene'),(select mineral_id from minerals where name='Diopside'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Hedenbergite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic pyroxene'),(select mineral_id from minerals where name='Hedenbergite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Augite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic pyroxene'),(select mineral_id from minerals where name='Augite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sodic pyroxene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic pyroxene'),(select mineral_id from minerals where name='Sodic pyroxene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Jadeite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Jadeite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Acmite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Acmite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Omphacite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Omphacite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Aegirine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Aegirine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Spodumene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Spodumene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clinoenstatite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Clinoenstatite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Wollastonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Wollastonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pectolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Pectolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Rhodonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Rhodonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Bustamite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Bustamite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pyroxmangite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Pyroxmangite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sapphirine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Sapphirine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Aenigmatite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Aenigmatite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Amphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic pyroxene'),(select mineral_id from minerals where name='Amphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Orthoamphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Amphibole'),(select mineral_id from minerals where name='Orthoamphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Anthophyllite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthoamphibole'),(select mineral_id from minerals where name='Anthophyllite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Gedrite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthoamphibole'),(select mineral_id from minerals where name='Gedrite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clinoamphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthoamphibole'),(select mineral_id from minerals where name='Clinoamphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Fe-Mg clinoamphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clinoamphibole'),(select mineral_id from minerals where name='Fe-Mg clinoamphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Cummingtonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Mg clinoamphibole'),(select mineral_id from minerals where name='Cummingtonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Grunerite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Mg clinoamphibole'),(select mineral_id from minerals where name='Grunerite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Calcic amphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Mg clinoamphibole'),(select mineral_id from minerals where name='Calcic amphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Tremolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic amphibole'),(select mineral_id from minerals where name='Tremolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Actinolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic amphibole'),(select mineral_id from minerals where name='Actinolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Hornblende');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic amphibole'),(select mineral_id from minerals where name='Hornblende'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Kaersutite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic amphibole'),(select mineral_id from minerals where name='Kaersutite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sodic Amphibole');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Calcic amphibole'),(select mineral_id from minerals where name='Sodic Amphibole'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Sodic Amphibole'), 'Blue Amphibole');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Glaucophane');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Glaucophane'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Riebeckite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Riebeckite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Richterite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Richterite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Katophorite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Katophorite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ekermannite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Ekermannite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Arfvedsonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sodic Amphibole'),(select mineral_id from minerals where name='Arfvedsonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ortho- and Ring Silicates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Clinoamphibole'),(select mineral_id from minerals where name='Ortho- and Ring Silicates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Olivine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Olivine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Humite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Humite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Zircon');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Zircon'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sphene');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Sphene'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Sphene'), 'Titanite');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Garnet');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Garnet'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Vesuvanite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Vesuvanite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sillimanite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Sillimanite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Andalusite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Andalusite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Kyanite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Kyanite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Mullite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Mullite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Topaz');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Topaz'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Staurolite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Staurolite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Chloritoid');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Chloritoid'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Larnite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Larnite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Merwinite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Merwinite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Spurrite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Spurrite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Epidote Group');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Ortho- and Ring Silicates'),(select mineral_id from minerals where name='Epidote Group'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Zoisite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Zoisite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Clinozoisite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Clinozoisite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Epidote');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Epidote'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Piemontite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Piemontite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Allanite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Allanite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Lawsonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Lawsonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pumpellyite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Pumpellyite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Melilite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Melilite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Rankinite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Rankinite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Tilleyite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Tilleyite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Beryl');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Beryl'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Cordierite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Cordierite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Tourmaline');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Tourmaline'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Axinite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Epidote Group'),(select mineral_id from minerals where name='Axinite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Oxides');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Orthoamphibole'),(select mineral_id from minerals where name='Oxides'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ilmenite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Oxides'),(select mineral_id from minerals where name='Ilmenite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Hematite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Oxides'),(select mineral_id from minerals where name='Hematite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Rutile');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Oxides'),(select mineral_id from minerals where name='Rutile'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Spinel Group');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Oxides'),(select mineral_id from minerals where name='Spinel Group'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'),(select mineral_id from minerals where name='Spinel Group'), 'Spinel');
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Spinel');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Spinel'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Magnetite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Magnetite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Chromite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Chromite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Hercynite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Hercynite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ghanite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Ghanite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Periclase');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Periclase'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Cassiterite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Cassiterite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Corundum');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Corundum'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Anatase');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Anatase'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Brookite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Brookite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Perovskite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Perovskite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Hydroxides');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Spinel Group'),(select mineral_id from minerals where name='Hydroxides'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Brucite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Brucite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Gibbsite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Gibbsite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Diaspore');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Diaspore'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Boehmite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Boehmite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Goethite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Goethite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Lepidocrocite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Lepidocrocite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Limonite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Limonite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sulphides');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Hydroxides'),(select mineral_id from minerals where name='Sulphides'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pyrite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Pyrite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Pyrrhotite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Pyrrhotite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Chalcopyrite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Chalcopyrite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sphalerite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Sphalerite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Galena');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Galena'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Sulphates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphides'),(select mineral_id from minerals where name='Sulphates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Baryte');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphates'),(select mineral_id from minerals where name='Baryte'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Celestine');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphates'),(select mineral_id from minerals where name='Celestine'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Gypsum');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphates'),(select mineral_id from minerals where name='Gypsum'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Anhydrite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphates'),(select mineral_id from minerals where name='Anhydrite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Carbonates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Sulphates'),(select mineral_id from minerals where name='Carbonates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Calcite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Calcite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Dolomite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Dolomite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Magnesite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Magnesite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Rhodochrosite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Rhodochrosite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Siderite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Siderite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Ankerite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Ankerite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Phosphates');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Phosphates'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Apatite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Phosphates'),(select mineral_id from minerals where name='Apatite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Monazite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Phosphates'),(select mineral_id from minerals where name='Monazite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Xenotime');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Phosphates'),(select mineral_id from minerals where name='Xenotime'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Native Elements');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbonates'),(select mineral_id from minerals where name='Native Elements'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Carbon');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Native Elements'),(select mineral_id from minerals where name='Carbon'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Graphite');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbon'),(select mineral_id from minerals where name='Graphite'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Diamond');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Carbon'),(select mineral_id from minerals where name='Diamond'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Other');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Native Elements'),(select mineral_id from minerals where name='Other'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Opaque');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Other'),(select mineral_id from minerals where name='Opaque'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Ilmenite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Hematite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Rutile'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Magnetite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Pyrite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Pyrrhotite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Chalcopyrite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Sphalerite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Galena'));
insert into minerals (mineral_id, real_mineral_id, name)  VALUES (nextval('mineral_seq'), currval('mineral_seq'), 'Fe-Ti oxide');
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Opaque'),(select mineral_id from minerals where name='Fe-Ti oxide'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Ti oxide'),(select mineral_id from minerals where name='Ilmenite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Ti oxide'),(select mineral_id from minerals where name='Hematite'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Ti oxide'),(select mineral_id from minerals where name='Rutile'));
insert into mineral_relationships (parent_mineral_id, child_mineral_id) VALUES((select mineral_id from minerals where name='Fe-Ti oxide'),(select mineral_id from minerals where name='Magnetite'));
